---
title: "economist-charts"
author: "Debi Gonzalez"
date: "April 11, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readxl)
library(janitor)
library(tidyverse)
library(gt)
library(fs)
library(ggthemes)
```

```{r Data Setup, echo = FALSE}
data <- read_csv("http://infographics.economist.com/databank/Economist_eu-balance.csv",
                 col_types = cols(Country = col_character(),
                  `Current-account balance, euro million` = col_double(),
                  `Current-account balance, euro million_1` = col_double(),
                  `Current-account balance, euro million_2` = col_double(),
                  `Current-account balance, euro million_3` = col_double(),
                  `Current-account balance, euro million_4` = col_double(),
                  `Current-account balance, euro million_5` = col_double(),
                  `Current-account balance, euro million_6` = col_double(),
                  `Budget balance, euro million` = col_double(),
                  `Budget balance, euro million_1` = col_double(),
                  `Budget balance, euro million_2` = col_double(),
                  `Budget balance, euro million_3` = col_double(),
                  `Budget balance, euro million_4` = col_double(),
                  `Budget balance, euro million_5` = col_double(),
                  `Budget balance, euro million_6` = col_double()),
                 skip = 1) %>% 
  mutate(country = case_when(Country == "Germany" ~ "Germany",
                           Country == "Greece" ~ "Greece", 
                           Country == "Netherlands" ~ "Netherlands",
                           Country == "Spain" ~ "Spain",
                           TRUE ~ "Other")) %>% 
  group_by(country)
    

# first one is current account
# second one is budget balance
 

```

```{r}

```

